

- name: Check Exchange ISO exists
  win_stat:
    path: C:\temp\ExchangeServer2016-x64-CU21.ISO
  register: exchange_stat

- name: Download Exchange Server 2016 CU21
  win_get_url:
    url: https://download.microsoft.com/download/7/d/5/7d5c319b-510b-4a2c-a77a-099c6f30ab54/ExchangeServer2016-x64-CU21.ISO
    dest: C:\temp\ExchangeServer2016-x64-CU21.ISO
    use_proxy: no
    timeout: 300
  when: exchange_stat.stat.exists == false

- name: Mount Exchange image
  community.windows.win_disk_image:
    image_path: C:\temp\ExchangeServer2016-x64-CU21.ISO
    state: present
  register: disk_image_out

- name: Prepare Schema
  win_shell: Setup.exe /PrepareSchema /IAcceptExchangeServerLicenseTerms
  args:
    chdir: "{{disk_image_out.mount_paths[0]}}"
    executable: cmd
  vars:
   ansible_become_user: "{{domain_admin_user}}"
   ansible_become_password: "{{domain_admin_password}}"

- name: Run Exchange Installer
  win_shell: Setup.exe /Mode:Install /Roles:Mailbox /OrganizationName:{{netbios_domain_name}} /DisableAMFiltering /IAcceptExchangeServerLicenseTerms
  args:
    chdir: "{{disk_image_out.mount_paths[0]}}"
    executable: cmd
  vars:
   ansible_become_user: "{{domain_admin_user}}"
   ansible_become_password: "{{domain_admin_password}}"
  register: Exchange_install

- name: Reboot after Installation
  win_reboot:
  when: Exchange_install.rc == 0

