- name: Create Temp Directory
  ansible.windows.win_file:
    path: C:\temp
    state: directory

- name: Install Windows Features for SQL Server
  ansible.windows.win_feature:
    name:
    - NET-Framework-Features
    state: present
  register: res

- name: Configure SQL Firewall
  community.windows.win_firewall_rule:
    name: "{{item.name}}"
    localport: "{{item.port}}"
    action: "{{item.action}}"
    direction: "{{item.dir}}"
    protocol: "{{item.protocol}}"
    state: present
    enabled: yes
  with_items: "{{Firewall_Rules}}"

- name: Allow ICMP
  community.windows.win_firewall_rule:
    name: ICMP
    action: allow
    direction: in
    protocol: icmpv4:8
    remoteip: any
    state: present
    enabled: yes

- name: Reboot after installing Windows Features
  win_reboot: