
- name: Set Windows Client DNS Settings
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - "{{DC}}"
    - "{{secondary_dns_server}}"
  retries: 10
  delay: 30

- name: Join Computer to Domain
  win_domain_membership:
    dns_domain_name: "{{dc_domain_name}}"
    domain_admin_user: "{{domain_admin_user}}"
    domain_admin_password: "{{domain_admin_password}}"
    state: domain
  register: domain_state

- win_reboot:
  when: domain_state.reboot_required
