
- name: Download Visual C++
  win_get_url:
    url: https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
    dest: C:\temp\vcredist_x64.exe
    use_proxy: no
    timeout: 300

- name: Run C++ installer
  raw: C:\temp\vcredist_x64.exe /q /norestart /log C:\temp\logC.txt /x86 /x64 /redist
  register: InstallC
  become: yes
  become_method: runas
  vars:
   ansible_become_user: "{{domain_admin_user}}"
   ansible_become_password: "{{domain_admin_password}}"

- name: Download Visual C++ 2013
  win_get_url:
    url: https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe
    dest: C:\temp\vcredist_x64_2013.exe
    use_proxy: no
    timeout: 300

- name: Run C++ 2013 installer
  win_shell: vcredist_x64_2013.exe /q /norestart /log C:\temp\logC.txt /x86 /x64 /redist
  args:
    chdir: C:\temp\
    executable: cmd
  register: InstallC13
  become: yes
  become_method: runas
  vars:
   ansible_become_user: "{{domain_admin_user}}"
   ansible_become_password: "{{domain_admin_password}}"

- name: Reboot after Installation
  win_reboot:

